{{- if $.Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "temporal-bench.serviceMonitor.name" . }}
  labels:
    app.kubernetes.io/name: temporal-bench
    helm.sh/chart: temporal-bench-1.16.0
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  endpoints:
  - port: metrics
    interval: {{ $.Values.serviceMonitor.interval }}
    metricRelabelings:
      - sourceLabels: [exported_namespace]
        targetLabel: temporal_namespace
        action: replace
  jobLabel: {{ $.Chart.Name }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "temporal-bench.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/headless: 'true'
---
{{- end }}
